# Generated by Django 4.2.10 on 2025-09-20 18:33

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(default=portal.models.custom_request_reference, editable=False, max_length=20, unique=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('machine_type', models.CharField(max_length=180)),
                ('capacity_requirement', models.CharField(blank=True, max_length=180)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('project_location', models.CharField(blank=True, max_length=160)),
                ('deployment_timeline', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('preferred_contact_method', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('quoted', 'Quoted'), ('fulfilled', 'Fulfilled')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=60)),
                ('feature_statement', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=portal.models.generate_machine_code, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('key_features', models.TextField(blank=True, help_text='Use bullet points separated by new lines.')),
                ('model_number', models.CharField(blank=True, max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('power_rating_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Kilowatt rating if applicable.', max_digits=7, null=True)),
                ('capacity_output', models.CharField(blank=True, help_text='e.g. 5,000 bottles/hr or 40 TPH', max_length=120)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('lead_time_weeks', models.PositiveIntegerField(default=8)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In Stock'), ('back_order', 'Backorder'), ('custom_build', 'Custom Build')], default='in_stock', max_length=20)),
                ('highlight_text', models.CharField(blank=True, max_length=120)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='machines/hero/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='machines/brochures/')),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('financing_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='portal.category')),
                ('industries', models.ManyToManyField(blank=True, related_name='machines', to='portal.industry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Titan Nexus Industrial Supply', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Powering production with precision partnerships.', max_length=160)),
                ('hero_title', models.CharField(default='Heavy Machinery, Delivered with Intelligence', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='From turnkey fabrication lines to bespoke automation, we orchestrate the machinery supply chain for world-class manufacturers.')),
                ('primary_cta_label', models.CharField(default='Explore Catalogue', max_length=80)),
                ('primary_cta_link', models.CharField(default='/catalogue/', max_length=200)),
                ('secondary_cta_label', models.CharField(blank=True, default='Request Custom Build', max_length=80)),
                ('secondary_cta_link', models.CharField(blank=True, default='/custom-request/', max_length=200)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('about_title', models.CharField(default='Engineering Procurement Reinvented', max_length=150)),
                ('about_body', models.TextField(blank=True)),
                ('experience_highlight', models.CharField(blank=True, default='Global supplier network across 18 countries with ISO-compliant partner factories.', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=18)),
                ('machines_deployed', models.PositiveIntegerField(default=450)),
                ('uptime_commitment', models.CharField(default='99.2% fleet uptime guarantee', max_length=120)),
                ('response_time', models.CharField(default='Quote turnaround in under 24 hours', max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('operation_regions', models.CharField(blank=True, help_text='Comma separated list of primary regions served.', max_length=180)),
                ('support_hours', models.CharField(blank=True, default='Global support 24/7', max_length=120)),
                ('newsletter_blurb', models.CharField(blank=True, max_length=255)),
                ('promo_video_url', models.URLField(blank=True)),
                ('footer_statement', models.CharField(blank=True, default='Certified general order supplier serving heavy industry since 2006.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_props', to='portal.sitesettings')),
            ],
            options={
                'verbose_name': 'Value proposition',
                'verbose_name_plural': 'Value propositions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_role', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('highlight', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portal.industry')),
            ],
            options={
                'ordering': ['-highlight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('quoted', 'Quoted'), ('fulfilled', 'Fulfilled')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='portal.customrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='machines/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portal.machine')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('document', models.FileField(upload_to='machines/documents/')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.machine')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='HeroMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fa-solid fa-industry', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portal.sitesettings')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='customrequest',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='portal.industry'),
        ),
    ]
